on: [push]

name: AzArmDeploy

jobs: 
  deploy:
    runs-on: ubunto-latest
    steps:
      - name: azure/login@v1
        uses: 
          creds: ${{AZ_SERVICE_PRINCIPAL.AZURE_CREDENTIALS}}
      - name: Code check
        uses: action/checkout@v2
      - name: Deploy ARM Template
        uses: azure/CLI@v1
        with: 
          inlineScript: |
            az deployment group create 
            -- name StorageAccountDeployment
            --resource-group savedevgithubdeploy
            --template-file armtemplates/storageaccounts.json
            --parameters storageAccountType=Standard_GRS
